/*Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.*/

public class TriPenHex
{
	public static void main(String[] args) {
		long hex = 147;
		long hexTerm = 0;

		while(true)
		{
			hexTerm = hex*(2*hex - 1);
			if(isPentagonal(hexTerm))
				break;
			hex++;
		}

		System.out.println(hexTerm);
	}

	private static boolean isPentagonal(long number) {
	    double penTest = (Math.sqrt(1 + 24 * number) + 1.0) / 6.0;
	    return penTest == ((long)penTest);
	}

}